import type { Metadata } from 'next';

import Navbar from '@components/Navbar';

import { Amiko, Inter } from 'next/font/google';
import { InViewProvider } from './context';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const noto_sans = Inter({
  subsets: ['latin'],
  weight: ['700', '500'],
  display: 'swap',
  variable: '--font-noto-sans',
});

const amiko = Amiko({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-amiko',
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={`${noto_sans.variable} ${amiko.className}`}>
      <body>
        <InViewProvider>
          <Navbar />
          {children}
        </InViewProvider>
      </body>
    </html>
  );
};

export default RootLayout;
